### ISSUE TITLE
 Logout functionality bug on certain pages after successful sign in

### ISSUE THREAD

**Issue by sangamdumre** [anupdangi21/LocalFarmers2#29]
After logging in, some pages don't let you log out properly. This can be frustrating and even risky, especially if you're using a shared computer. To fix it, we need to find out which pages are affected and then fix the problem in the code. After that, we'll test to make sure you can log out from any page without any trouble. Once everything's working smoothly, we'll update the app for everyone to use safely.

**Comment by AB-octo** [comment]
This commit addresses a bug that caused the logout feature to malfunction on specific pages, preventing users from logging out properly. The problem was identified in the code, and necessary fixes were implemented to ensure the logout functionality works reliably across all pages. Thorough testing has been performed to validate the fix. With this resolution, users can now securely log out from any page without any disruptions.
